### ISSUE TITLE
Xournal++ crashed during moving a selection

### ISSUE THREAD

**Issue by ericschdt** [xournalpp/xournalpp#2487]
**Affects versions :**
 - OS: Manjaro KDE
 - (Linux only) Desktop environment: X11
 - Which version of libgtk do you use
      libgtk: 3.24.23 

 - Version of Xournal++: fad337b3
 - Installation method: AUR
- `New input method` is activated (I think I used the mouse for dragging, though)

**Describe the bug**
I copied and pasted a selection which I dragged within the document when Xournal++ crashed.
I cannot reproduce it always. It happens around 1-2 a day while I use Xournal++ for some hours.

**Full stack trace**

```
Thread 1 "xournalpp" received signal SIGSEGV, Segmentation fault.
0x00007efd01044aff in gtk_widget_queue_draw () from /usr/lib/libgtk-3.so.0
(gdb) thread apply all bt

Thread 15 (Thread 0x7efcc6ffd640 (LWP 18883) "dconf worker"):
#0  0x00007efd0010746f in poll () at /usr/lib/libc.so.6
#1  0x00007efd0155975f in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007efd01504121 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007efcf8765c0e in  () at /usr/lib/gio/modules/libdconfsettings.so
#4  0x00007efd01532ce1 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007efd0061f3e9 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007efd00112293 in clone () at /usr/lib/libc.so.6

Thread 5 (Thread 0x7efcfa099640 (LWP 15323) "threaded-ml"):
#0  0x00007efd0010746f in poll () at /usr/lib/libc.so.6
#1  0x00007efcfa0e0654 in  () at /usr/lib/libpulse.so.0
#2  0x00007efcfa0c99a9 in pa_mainloop_poll () at /usr/lib/libpulse.so.0
#3  0x00007efcfa0d4281 in pa_mainloop_iterate () at /usr/lib/libpulse.so.0
#4  0x00007efcfa0d4331 in pa_mainloop_run () at /usr/lib/libpulse.so.0
#5  0x00007efcfa0e47fe in  () at /usr/lib/libpulse.so.0
#6  0x00007efcf986a5fc in  () at /usr/lib/pulseaudio/libpulsecommon-14.0.so
#7  0x00007efd0061f3e9 in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007efd00112293 in clone () at /usr/lib/libc.so.6

Thread 4 (Thread 0x7efcfaa04640 (LWP 15322) "xournalpp"):
#0  0x00007efd00adcd0d in  () at /usr/lib/libcairo.so.2
#1  0x00007efd00acb6af in  () at /usr/lib/libcairo.so.2
#2  0x00007efd00accd81 in  () at /usr/lib/libcairo.so.2
#3  0x00007efd00a85bff in  () at /usr/lib/libcairo.so.2
#4  0x00007efd00a98f6e in  () at /usr/lib/libcairo.so.2
#5  0x00007efd00ad9cd6 in  () at /usr/lib/libcairo.so.2
#6  0x00007efd00a8ecc4 in  () at /usr/lib/libcairo.so.2
#7  0x00007efd00a879ca in  () at /usr/lib/libcairo.so.2
#8  0x00007efd00ae79ea in cairo_stroke () at /usr/lib/libcairo.so.2
#9  0x0000558e3f41865e in StrokeView::drawWithPressure() (this=0x7efcfaa03740) at /path/to/AUR/xournalpp-git/src/xournalpp/src/view/StrokeView.cpp:122
#10 0x0000558e3f416e8b in DocumentView::drawStroke(_cairo*, Stroke*, int, double, bool, bool) const (this=0x7efcfaa03880, cr=0x558e41468580, s=0x558e41d6c760, startPoint=0, scaleFactor=6.8983916621855538e-310, changeSource=<optimized out>, noAlpha=<optimized out>) at /path/to/AUR/xournalpp-git/src/xournalpp/src/view/DocumentView.cpp:57
#11 0x0000558e3f417533 in DocumentView::drawLayer(_cairo*, Layer*) (this=this@entry=0x7efcfaa03880, cr=cr@entry=0x558e41468580, l=l@entry=0x558e418b09d0) at /path/to/AUR/xournalpp-git/src/xournalpp/src/view/DocumentView.cpp:185
#12 0x0000558e3f417d6e in DocumentView::drawPage(std::shared_ptr<XojPage>, _cairo*, bool, bool) (this=this@entry=0x7efcfaa03880, page=std::shared_ptr<XojPage> (use count 218, weak count 1) = {...}, cr=cr@entry=0x558e41468580, dontRenderEditingStroke=dontRenderEditingStroke@entry=false, hideBackground=hideBackground@entry=false) at /path/to/AUR/xournalpp-git/src/xournalpp/src/view/DocumentView.cpp:327
#13 0x0000558e3f335216 in RenderJob::run() (this=0x558e42de8190) at /path/to/AUR/xournalpp-git/src/xournalpp/src/control/jobs/RenderJob.cpp:120
#14 0x0000558e3f336e7e in Scheduler::jobThreadCallback(Scheduler*) (scheduler=0x558e40e18800) at /path/to/AUR/xournalpp-git/src/xournalpp/src/control/jobs/Scheduler.cpp:247
--Type <RET> for more, q to quit, c to continue without paging--
#15 0x00007efd01532ce1 in  () at /usr/lib/libglib-2.0.so.0
#16 0x00007efd0061f3e9 in start_thread () at /usr/lib/libpthread.so.0
#17 0x00007efd00112293 in clone () at /usr/lib/libc.so.6

Thread 3 (Thread 0x7efcfb46c640 (LWP 15308) "gdbus"):
#0  0x00007efd0010746f in poll () at /usr/lib/libc.so.6
#1  0x00007efd0155975f in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007efd01504e63 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#3  0x00007efd00981fe8 in  () at /usr/lib/libgio-2.0.so.0
#4  0x00007efd01532ce1 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007efd0061f3e9 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007efd00112293 in clone () at /usr/lib/libc.so.6

Thread 2 (Thread 0x7efcfbc6d640 (LWP 15307) "gmain"):
#0  0x00007efd0010746f in poll () at /usr/lib/libc.so.6
#1  0x00007efd0155975f in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007efd01504121 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007efd01504172 in  () at /usr/lib/libglib-2.0.so.0
#4  0x00007efd01532ce1 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007efd0061f3e9 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007efd00112293 in clone () at /usr/lib/libc.so.6

Thread 1 (Thread 0x7efcfc0ccbc0 (LWP 15306) "xournalpp"):
#0  0x00007efd01044aff in gtk_widget_queue_draw () at /usr/lib/libgtk-3.so.0
#1  0x0000558e3f333fe5 in operator() (__closure=0x558e41e93a80) at /path/to/AUR/xournalpp-git/src/xournalpp/src/control/jobs/PreviewJob.cpp:46
#2  std::__invoke_impl<void, PreviewJob::finishPaint()::<lambda()>&> (__f=...) at /usr/include/c++/10.2.0/bits/invoke.h:60
#3  std::__invoke_r<void, PreviewJob::finishPaint()::<lambda()>&> (__fn=...) at /usr/include/c++/10.2.0/bits/invoke.h:110
#4  std::_Function_handler<void(), PreviewJob::finishPaint()::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/10.2.0/bits/std_function.h:291
#5  0x0000558e3f426c1e in std::function<void ()>::operator()() const (this=0x558e41e93a80) at /usr/include/c++/10.2.0/bits/std_function.h:622
#6  execInUiThreadCallback(CallbackUiData*) (cb=0x558e41e93a80) at /path/to/AUR/xournalpp-git/src/xournalpp/src/util/Util.cpp:25
#7  0x00007efd00c398ac in  () at /usr/lib/libgdk-3.so.0
#8  0x00007efd01505914 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#9  0x00007efd015597d1 in  () at /usr/lib/libglib-2.0.so.0
#10 0x00007efd01504e63 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#11 0x00007efd00eec4ff in gtk_main () at /usr/lib/libgtk-3.so.0
#12 0x0000558e3f32b2bc in XournalMain::run(int, char**) (this=this@entry=0x558e40c78e10, argc=<optimized out>, argc@entry=1, argv=<optimized out>, argv@entry=0x7ffc81bfe8f8) at /path/to/AUR/xournalpp-git/src/xournalpp/src/control/XournalMain.cpp:414
#13 0x0000558e3f302667 in main(int, char**) (argc=1, argv=0x7ffc81bfe8f8) at /path/to/AUR/xournalpp-git/src/xournalpp/src/Xournalpp.cpp:42
```

**Comment by Technius** [comment]
Does this still happen with latest master?

**Comment by ericschdt** [comment]
Haven't seen it in a while, though also haven't used much Xournalpp recently. Will reopen if it happens again in the latest build.
