### ISSUE TITLE
Crash when using the text editor tool

### ISSUE THREAD

**Issue by Rio6** [xournalpp/xournalpp#3500]
**Affects versions :**
 - OS: Artix Linux
 - (Linux only) Desktop environment: X11, awesomewm
 - IM: gcin 2.9.0
 - Which version of libgtk do you use: 3.24.30
 - Version of Xournal++: Found on 1.1.0, git bisect points to c237d3e5f8f190cea9e4098e62cf7f7362a29ed8
 - Installation method: occurs both for Archlinux package and compile from source

**Describe the bug**
Xournal++ crashes when clicking on the page using text editor tool.

**To Reproduce**
1. Open Xournal++
2. Select text editor
3. Click anywhere on the page

**Expected behavior**
Text editor get activated on page.

**Screenshots of Problem**

https://user-images.githubusercontent.com/15951245/138579919-b393266e-0170-478f-b7b3-35626350ceed.mp4

**Additional context**
Following outputs are from c237d3e5f8f190cea9e4098e62cf7f7362a29ed8

Stdout:
```
(xournalpp:7646): Gdk-CRITICAL **: 00:10:15.007: gdk_device_get_source: assertion 'GDK_IS_DEVICE (device)' failed

(xournalpp:7646): Gdk-CRITICAL **: 00:10:15.007: gdk_device_get_name: assertion 'GDK_IS_DEVICE (device)' failed
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid

** (xournalpp:7646): WARNING **: 00:10:15.007: [Crash Handler] Crashed with signal 6
```
Log file:
```
Date: Sat Oct 23 23:50:32 2021
Error: signal 6
[bt]: (0) ./src/xournalpp(+0x431945) [0x55a05baf4945]
[bt]: (1) /usr/lib/libc.so.6(+0x3cf80) [0x7fc9d0b18f80]
[bt]: (2) /usr/lib/libc.so.6(gsignal+0x145) [0x7fc9d0b18ef5]
[bt]: (3) /usr/lib/libc.so.6(abort+0x116) [0x7fc9d0b02862]
[bt]: (4) /usr/lib/libstdc++.so.6(+0x99802) [0x7fc9d0d5d802]
[bt]: (5) /usr/lib/libstdc++.so.6(+0xa5c8a) [0x7fc9d0d69c8a]
[bt]: (6) /usr/lib/libstdc++.so.6(+0xa5cf7) [0x7fc9d0d69cf7]
[bt]: (7) /usr/lib/libstdc++.so.6(+0xa5f8e) [0x7fc9d0d69f8e]
[bt]: (8) /usr/lib/libstdc++.so.6(_ZSt19__throw_logic_errorPKc+0x45) [0x7fc9d0d6036c]
[bt]: (9) ./src/xournalpp(_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12_M_constructIPKcEEvT_S8_St20forward_iterator_tag+0x5d) [0x55a05b92cb17]
[bt]: (10) ./src/xournalpp(_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE16_M_construct_auxIPKcEEvT_S8_St12__false_type+0x3a) [0x55a05b92ca72]
[bt]: (11) ./src/xournalpp(_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12_M_constructIPKcEEvT_S8_+0x2b) [0x55a05b92ca35]
[bt]: (12) ./src/xournalpp(_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC2IS3_EEPKcRKS3_+0x71) [0x55a05b92c9e7]
[bt]: (13) ./src/xournalpp(_ZN11InputEvents19translateDeviceTypeEP10_GdkDeviceP8Settings+0x5c) [0x55a05ba72cc4]
[bt]: (14) ./src/xournalpp(_ZN11InputEvents14translateEventEP9_GdkEventP8Settings+0xa1) [0x55a05ba72ddb]
[bt]: (15) ./src/xournalpp(_ZN12InputContext6handleEP9_GdkEvent+0x71) [0x55a05ba713af]
[bt]: (16) ./src/xournalpp(_ZN12InputContext13eventCallbackEP10_GtkWidgetP9_GdkEventPS_+0x27) [0x55a05ba7133b]
[bt]: (17) /usr/lib/libgtk-3.so.0(+0x87bb9) [0x7fc9d1abcbb9]
[bt]: (18) /usr/lib/libgobject-2.0.so.0(g_signal_emit_valist+0x12c6) [0x7fc9d145bc96]
[bt]: (19) /usr/lib/libgobject-2.0.so.0(g_signal_emit+0x94) [0x7fc9d145be04]
[bt]: (20) /usr/lib/libgtk-3.so.0(+0x34510e) [0x7fc9d1d7a10e]
[bt]: (21) /usr/lib/libgtk-3.so.0(gtk_main_do_event+0x85a) [0x7fc9d1c1784a]
[bt]: (22) /usr/lib/libgdk-3.so.0(+0x3cd43) [0x7fc9d197bd43]
[bt]: (23) /usr/lib/libgdk-3.so.0(+0x892a8) [0x7fc9d19c82a8]
[bt]: (24) /usr/lib/libglib-2.0.so.0(g_main_context_dispatch+0x26c) [0x7fc9d224209c]
[bt]: (25) /usr/lib/libglib-2.0.so.0(+0xaa7f9) [0x7fc9d22977f9]
[bt]: (26) /usr/lib/libglib-2.0.so.0(g_main_context_iteration+0x35) [0x7fc9d223f6e5]
[bt]: (27) /usr/lib/libgio-2.0.so.0(g_application_run+0x1ae) [0x7fc9d156047e]
[bt]: (28) ./src/xournalpp(_ZN11XournalMain3runEiPPc+0x71f) [0x55a05b96c87f]
[bt]: (29) ./src/xournalpp(main+0x25) [0x55a05b92c24e]
[bt]: (30) /usr/lib/libc.so.6(__libc_start_main+0xd5) [0x7fc9d0b03b25]
[bt]: (31) ./src/xournalpp(_start+0x2e) [0x55a05b92c15e]
```
gdb backtrace:
```
#0  0x00007ffff6647ef5 in raise () at /usr/lib/libc.so.6
#1  0x00007ffff6631862 in abort () at /usr/lib/libc.so.6
#2  0x00007ffff688c802 in __gnu_cxx::__verbose_terminate_handler() () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007ffff6898c8a in __cxxabiv1::__terminate(void (*)()) (handler=<optimized out>) at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:48
#4  0x00007ffff6898cf7 in std::terminate() () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:58
#5  0x00007ffff6898f8e in __cxxabiv1::__cxa_throw(void*, std::type_info*, void (*)(void*)) (obj=<optimized out>, tinfo=0x7ffff69fb1a8 <typeinfo for std::logic_error>, dest=0x7ffff68aee80 <std::logic_error::~logic_error()>) at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:95
#6  0x00007ffff688f36c in std::__throw_logic_error(char const*) (__s=0x5555559a0110 "basic_string::_M_construct null not valid") at /build/gcc/src/gcc/libstdc++-v3/src/c++11/functexcept.cc:70
#7  0x00005555557bdb17 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char const*>(char const*, char const*, std::forward_iterator_tag) (this=0x7fffffffd600, __beg=0x0, __end=0xffffffffffffffff <error: Cannot access memory at address 0xffffffffffffffff>) at /usr/include/c++/11.1.0/bits/basic_string.tcc:212
#8  0x00005555557bda72 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct_aux<char const*>(char const*, char const*, std::__false_type) (this=0x7fffffffd600, __beg=0x0, __end=0xffffffffffffffff <error: Cannot access memory at address 0xffffffffffffffff>) at /usr/include/c++/11.1.0/bits/basic_string.h:247
#9  0x00005555557bda35 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char const*>(char const*, char const*) (this=0x7fffffffd600, __beg=0x0, __end=0xffffffffffffffff <error: Cannot access memory at address 0xffffffffffffffff>) at /usr/include/c++/11.1.0/bits/basic_string.h:266
#10 0x00005555557bd9e7 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string<std::allocator<char> >(char const*, std::allocator<char> const&) (this=0x7fffffffd600, __s=0x0, __a=...) at /usr/include/c++/11.1.0/bits/basic_string.h:527
#11 0x0000555555903cc4 in InputEvents::translateDeviceType(_GdkDevice*, Settings*) (device=0x0, settings=0x555555de9c00) at /home/rio/tmp/xournalpp/src/gui/inputdevices/InputEvents.cpp:72
#12 0x0000555555903ddb in InputEvents::translateEvent(_GdkEvent*, Settings*) (sourceEvent=0x555555b11700, settings=0x555555de9c00) at /home/rio/tmp/xournalpp/src/gui/inputdevices/InputEvents.cpp:85
#13 0x00005555559023af in InputContext::handle(_GdkEvent*) (this=0x555555ea7c00, sourceEvent=0x555555b11700) at /home/rio/tmp/xournalpp/src/gui/inputdevices/InputContext.cpp:71
#14 0x000055555590233b in InputContext::eventCallback(_GtkWidget*, _GdkEvent*, InputContext*) (widget=0x555555eb2120, event=0x555555b11700, self=0x555555ea7c00) at /home/rio/tmp/xournalpp/src/gui/inputdevices/InputContext.cpp:65
#15 0x00007ffff75ebbb9 in  () at /usr/lib/libgtk-3.so.0
#16 0x00007ffff6f8ac96 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#17 0x00007ffff6f8ae04 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#18 0x00007ffff78a910e in  () at /usr/lib/libgtk-3.so.0
#19 0x00007ffff774684a in gtk_main_do_event () at /usr/lib/libgtk-3.so.0
#20 0x00007ffff74aad43 in  () at /usr/lib/libgdk-3.so.0
#21 0x00007ffff74f72a8 in  () at /usr/lib/libgdk-3.so.0
#22 0x00007ffff7d7109c in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#23 0x00007ffff7dc67f9 in  () at /usr/lib/libglib-2.0.so.0
#24 0x00007ffff7d6e6e5 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#25 0x00007ffff708f47e in g_application_run () at /usr/lib/libgio-2.0.so.0
#26 0x00005555557fd87f in XournalMain::run(int, char**) (argc=0x1, argv=0x7fffffffe1c8) at /home/rio/tmp/xournalpp/src/control/XournalMain.cpp:684
#27 0x00005555557bd24e in main(int, char**) (argc=0x1, argv=0x7fffffffe1c8) at /home/rio/tmp/xournalpp/src/Xournalpp.cpp:41
```

**Comment by bhennion** [comment]
Fix via #3511 via #3599
