### ISSUE TITLE
crash opening save/export dialog after using text tool on wayland on rocky8

### ISSUE THREAD

**Issue by charkins** [xournalpp/xournalpp#4279]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Rocky Linux 8
 - (Linux only) Desktop environment: Wayland
 - Which version of libgtk do you use: 3.22.30
 - Version of Xournal++: v1.1.1 and master (b6de6969)
 - Installation method: EPEL rpm, local build from master (b6de6969)
 
**Describe the bug**

Opening xournalpp with a blank page and using the text tool will crash as soon as a save or export dialog is opened on wayland on Rocky 8. Same steps on X11 does not cause the crash.

**To Reproduce**
1. Launch xournalpp on wayland on rocky8.
2. Use text tool (e.g. enter "x" on page).
3. Attempt to save the document.

**Expected behavior**
Dialog opens and allows document to be saved/exported.

**Additional context**
I originally reported [the bug downstream](https://bugzilla.redhat.com/show_bug.cgi?id=2131874) against the EPEL 8 rpm before verifying the bug by building from git.

The relevant portion of the backtrace:
```
Thread 1 "xournalpp" received signal SIGSEGV, Segmentation fault.
__GI___libc_free (mem=mem@entry=0x1) at malloc.c:3110
3110      p = mem2chunk (mem);
(gdb) bt
#0  __GI___libc_free (mem=mem@entry=0x1) at malloc.c:3110
#1  0x00007ffff75b5582 in g_free (mem=0x1) at gmem.c:194
#2  0x00007ffff7021e0a in reset_preedit (context=0x555556082a70) at imwayland.c:107
#3  0x00007fffeeba614e in ffi_call_unix64 () at ../src/x86/unix64.S:76
#4  0x00007fffeeba5aff in ffi_call (cif=cif@entry=0x7fffffffb6f0, fn=<optimized out>, rvalue=<optimized out>, rvalue@entry=0x0, avalue=avalue@entry=0x7fffffffb7c0) at ../src/x86/ffi64.c:525
#5  0x00007ffff198b82d in wl_closure_invoke (closure=closure@entry=0x555555a62240, flags=flags@entry=1, target=<optimized out>, target@entry=0x555555a9b560, opcode=opcode@entry=1, data=<optimized out>)
    at src/connection.c:1018
#6  0x00007ffff1987e99 in dispatch_event (display=display@entry=0x555555a5d6d0, queue=<optimized out>) at src/wayland-client.c:1452
#7  0x00007ffff198942c in dispatch_queue (queue=0x555555a5d7a0, display=0x555555a5d6d0) at src/wayland-client.c:1598
#8  wl_display_dispatch_queue_pending (display=0x555555a5d6d0, queue=0x555555a5d7a0) at src/wayland-client.c:1840
#9  0x00007ffff1989490 in wl_display_dispatch_pending (display=<optimized out>) at src/wayland-client.c:1903
#10 0x00007ffff69df298 in _gdk_wayland_display_queue_events (display=<optimized out>) at gdkeventsource.c:201
#11 0x00007ffff697dc44 in gdk_display_get_event (display=display@entry=0x555555a63050) at gdkdisplay.c:438
#12 0x00007ffff69defa6 in gdk_event_source_dispatch (base=<optimized out>, callback=<optimized out>, data=<optimized out>) at gdkeventsource.c:120
#13 0x00007ffff75af95d in g_main_dispatch (context=0x555555a3b0c0) at gmain.c:3193
#14 g_main_context_dispatch (context=context@entry=0x555555a3b0c0) at gmain.c:3873
#15 0x00007ffff75afd18 in g_main_context_iterate (context=0x555555a3b0c0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3946
#16 0x00007ffff75b0042 in g_main_loop_run (loop=0x5555562ed010) at gmain.c:4142
#17 0x00007ffff6dee2f7 in gtk_dialog_run (dialog=0x5555562b0350) at gtkdialog.c:1401
#18 0x0000555555621e90 in Control::showSaveDialog (this=0x555555aca000) at /usr/src/debug/xournalpp-1.1.1-1.el8.x86_64/src/control/Control.cpp:2324
#19 0x0000555555622855 in Control::save (this=0x555555aca000, synchron=<optimized out>) at /usr/src/debug/xournalpp-1.1.1-1.el8.x86_64/src/control/Control.cpp:2278
```

This backtrace is similar to one [reported against webkit](https://bugs.webkit.org/show_bug.cgi?id=185818) relating to the IM context and focus.

**Comment by rolandlo** [comment]
Fixed by #4820
