### ISSUE TITLE
Xournalpp crashes when expanding selection area to the scrollbar (assertion error)

### ISSUE THREAD

**Issue by mesonium** [xournalpp/xournalpp#4902]
**Affects versions :**
 - OS: openSUSE TW
 - (Linux only) Desktop environment: Wayland
 - Which version of libgtk do you use: 3.24.38
 - Version of Xournal++: 1.1.3+dev (git commit 037c5d99)
 - Installation method: Source

**Describe the bug**
Rectangular region selection tool and Wacom Intuos M: selecting an area which covers the scrollbar on the right lets  Xournal++ crash. This crash is reproducible.

**Additional context**

```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007ffff5a94993 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007ffff5a43196 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff5a2b897 in __GI_abort () at abort.c:79
#4  0x00007ffff5a2b7ab in __assert_fail_base (fmt=0x7ffff5bb1bb8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0xa15640 "settings->getInputSystemTPCButtonEnabled() && \"the selection has already been created by a stylus button press while the stylus was \" \"hovering!\"", file=0xa15508 "/home/user/dev/xournalpp/src/core/gui/PageView.cpp", line=306, function=<optimized out>) at assert.c:92
#5  0x00007ffff5a3b4b6 in __assert_fail (assertion=0xa15640 "settings->getInputSystemTPCButtonEnabled() && \"the selection has already been created by a stylus button press while the stylus was \" \"hovering!\"", file=0xa15508 "/home/user/dev/xournalpp/src/core/gui/PageView.cpp", line=306, function=0xa15600 "bool XojPageView::onButtonPressEvent(const PositionInputData&)") at assert.c:101
#6  0x00000000008f3918 in XojPageView::onButtonPressEvent(PositionInputData const&) ()
#7  0x0000000000800566 in PenInputHandler::actionStart(InputEvent const&) ()
#8  0x0000000000802d29 in StylusInputHandler::handleImpl(InputEvent const&) ()
#9  0x000000000092889f in AbstractInputHandler::handle(InputEvent const&) ()
#10 0x00000000007fd349 in InputContext::handle(_GdkEvent*) ()
#11 0x00000000007fcfb5 in InputContext::eventCallback(_GtkWidget*, _GdkEvent*, InputContext*) ()
#12 0x00007ffff689ad04 in _gtk_marshal_BOOLEAN__BOXEDv (closure=0x1127810, return_value=0x7fffffffd5a0, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0xbb4aa0) at gtk/gtkmarshalers.c:130
#13 0x00007ffff63a8641 in _g_closure_invoke_va (closure=0x1127810, return_value=0x7fffffffd5a0, instance=0xcd91d0, args=0x7fffffffd670, n_params=1, param_types=0xbb4aa0) at ../gobject/gclosure.c:895
#14 0x00007ffff63c1b92 in g_signal_emit_valist (instance=0xcd91d0, signal_id=91, detail=0, var_args=var_args@entry=0x7fffffffd670) at ../gobject/gsignal.c:3472
#15 0x00007ffff63c29df in g_signal_emit (instance=instance@entry=0xcd91d0, signal_id=<optimized out>, detail=detail@entry=0) at ../gobject/gsignal.c:3622
#16 0x00007ffff6b4f9e6 in gtk_widget_event_internal.part.0.lto_priv.0 (widget=0xcd91d0 [GtkXournal], event=0x13025f0) at ../gtk/gtkwidget.c:7699
#17 0x00007ffff69f82ee in propagate_event_up (topmost=<optimized out>, event=<optimized out>, widget=0xcd91d0 [GtkXournal]) at ../gtk/gtkmain.c:2588
#18 propagate_event (widget=widget@entry=0xcd91d0 [GtkXournal], event=event@entry=0x13025f0, captured=captured@entry=0, topmost=topmost@entry=0x0) at ../gtk/gtkmain.c:2691
#19 0x00007ffff69f840c in gtk_propagate_event (event=0x13025f0, widget=0xcd91d0 [GtkXournal]) at ../gtk/gtkmain.c:2725
#20 0x00007ffff69f8dc6 in gtk_main_do_event (event=0x13025f0) at ../gtk/gtkmain.c:1921
#21 gtk_main_do_event (event=<optimized out>) at ../gtk/gtkmain.c:1691
#22 0x00007ffff673f277 in _gdk_event_emit (event=0x13025f0) at ../gdk/gdkevents.c:73
#23 _gdk_event_emit (event=0x13025f0) at ../gdk/gdkevents.c:67
#24 0x00007ffff6774ac2 in gdk_event_source_dispatch (base=<optimized out>, callback=<optimized out>, data=<optimized out>) at ../gdk/wayland/gdkeventsource.c:124
#25 0x00007ffff62a78d8 in g_main_dispatch (context=0xbaacd0) at ../glib/gmain.c:3460
#26 g_main_context_dispatch (context=context@entry=0xbaacd0) at ../glib/gmain.c:4200
#27 0x00007ffff62a7ce8 in g_main_context_iterate (context=context@entry=0xbaacd0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4276
#28 0x00007ffff62a7d7c in g_main_context_iteration (context=context@entry=0xbaacd0, may_block=may_block@entry=1) at ../glib/gmain.c:4343
#29 0x00007ffff650583d in g_application_run (application=0xba8e10 [GtkApplication], argc=1, argv=<optimized out>) at ../gio/gapplication.c:2573
#30 0x000000000078b781 in XournalMain::run(int, char**) ()
#31 0x00000000007849ab in main ()
```

Please see also
<details>
<summary>bt full</summary>
<p>

```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
        tid = <optimized out>
        ret = 0
        pd = <optimized out>
        old_mask = {__val = {10573376}}
        ret = <optimized out>
#1  0x00007ffff5a94993 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007ffff5a43196 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
        ret = <optimized out>
#3  0x00007ffff5a2b897 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x20, sa_sigaction = 0x20}, sa_mask = {__val = {306, 23149936, 23149936, 304, 0, 51539594448, 140737488342216, 0, 15569291233730192896, 5, 18446744073709550568, 11, 10573064, 306, 10573376, 12274336}}, sa_flags = -173392461, sa_restorer = 0x7ffff5be7660 <__GI__IO_file_jumps>}
#4  0x00007ffff5a2b7ab in __assert_fail_base (fmt=0x7ffff5bb1bb8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0xa15640 "settings->getInputSystemTPCButtonEnabled() && \"the selection has already been created by a stylus button press while the stylus was \" \"hovering!\"", file=0xa15508 "/home/user/dev/xournalpp/src/core/gui/PageView.cpp", line=306, function=<optimized out>) at assert.c:92
        str = 0x1613d70 "s\326\\\001"
        total = 4096
#5  0x00007ffff5a3b4b6 in __assert_fail (assertion=0xa15640 "settings->getInputSystemTPCButtonEnabled() && \"the selection has already been created by a stylus button press while the stylus was \" \"hovering!\"", file=0xa15508 "/home/user/dev/xournalpp/src/core/gui/PageView.cpp", line=306, function=0xa15600 "bool XojPageView::onButtonPressEvent(const PositionInputData&)") at assert.c:101
#6  0x00000000008f3918 in XojPageView::onButtonPressEvent(PositionInputData const&) ()
#7  0x0000000000800566 in PenInputHandler::actionStart(InputEvent const&) ()
#8  0x0000000000802d29 in StylusInputHandler::handleImpl(InputEvent const&) ()
#9  0x000000000092889f in AbstractInputHandler::handle(InputEvent const&) ()
#10 0x00000000007fd349 in InputContext::handle(_GdkEvent*) ()
#11 0x00000000007fcfb5 in InputContext::eventCallback(_GtkWidget*, _GdkEvent*, InputContext*) ()
#12 0x00007ffff689ad04 in _gtk_marshal_BOOLEAN__BOXEDv (closure=0x1127810, return_value=0x7fffffffd5a0, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0xbb4aa0) at gtk/gtkmarshalers.c:130
        data1 = <optimized out>
        data2 = 0x1131b20
        callback = 0x7fcf8e <InputContext::eventCallback(_GtkWidget*, _GdkEvent*, InputContext*)>
        v_return = <optimized out>
        arg0 = 0x13025f0
        args_copy = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x7fffffffd750, reg_save_area = 0x7fffffffd690}}
        __func__ = "_gtk_marshal_BOOLEAN__BOXEDv"
#13 0x00007ffff63a8641 in _g_closure_invoke_va (closure=0x1127810, return_value=0x7fffffffd5a0, instance=0xcd91d0, args=0x7fffffffd670, n_params=1, param_types=0xbb4aa0) at ../gobject/gclosure.c:895
        marshal = 0x7ffff689ac70 <_gtk_marshal_BOOLEAN__BOXEDv>
        marshal_data = 0x0
        in_marshal = 0
        real_closure = 0x11277f0
        __func__ = "_g_closure_invoke_va"
#14 0x00007ffff63c1b92 in g_signal_emit_valist (instance=0xcd91d0, signal_id=91, detail=0, var_args=var_args@entry=0x7fffffffd670) at ../gobject/gsignal.c:3472
        return_accu = 0x7fffffffd5a0
        accu = {g_type = 0x14 [gboolean], data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        accumulator = 0xbca3f0
        emission = {next = 0x0, instance = 0xcd91d0, ihint = {signal_id = 91, detail = 0, run_type = (G_SIGNAL_RUN_FIRST | G_SIGNAL_ACCUMULATOR_FIRST_RUN)}, state = EMISSION_RUN, chain_type = 0x114e700 [GtkXournal/GtkWidget/GInitiallyUnowned]}
        instance_type = 0x114e700 [GtkXournal/GtkWidget/GInitiallyUnowned]
        emission_return = {g_type = 0x14 [gboolean], data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        rtype = 0x14 [gboolean]
        static_scope = 0
        fastpath_handler = <optimized out>
        closure = <optimized out>
        run_type = <optimized out>
        hlist = <optimized out>
        l = <optimized out>
        fastpath = <optimized out>
        instance_and_params = <optimized out>
        signal_return_type = <optimized out>
        param_values = <optimized out>
        node = <optimized out>
        i = <optimized out>
        n_params = <optimized out>
        __func__ = "g_signal_emit_valist"
#15 0x00007ffff63c29df in g_signal_emit (instance=instance@entry=0xcd91d0, signal_id=<optimized out>, detail=detail@entry=0) at ../gobject/gsignal.c:3622
        var_args = {{gp_offset = 24, fp_offset = 48, overflow_arg_area = 0x7fffffffd750, reg_save_area = 0x7fffffffd690}}
#16 0x00007ffff6b4f9e6 in gtk_widget_event_internal.part.0.lto_priv.0 (widget=0xcd91d0 [GtkXournal], event=0x13025f0) at ../gtk/gtkwidget.c:7699
        return_val = <optimized out>
        handled = 0
#17 0x00007ffff69f82ee in propagate_event_up (topmost=<optimized out>, event=<optimized out>, widget=0xcd91d0 [GtkXournal]) at ../gtk/gtkmain.c:2588
        tmp = <optimized out>
        handled_event = <optimized out>
        handled_event = 0
#18 propagate_event (widget=widget@entry=0xcd91d0 [GtkXournal], event=event@entry=0x13025f0, captured=captured@entry=0, topmost=topmost@entry=0x0) at ../gtk/gtkmain.c:2691
        handled_event = 0
#19 0x00007ffff69f840c in gtk_propagate_event (event=0x13025f0, widget=0xcd91d0 [GtkXournal]) at ../gtk/gtkmain.c:2725
        __func__ = "gtk_propagate_event"
#20 0x00007ffff69f8dc6 in gtk_main_do_event (event=0x13025f0) at ../gtk/gtkmain.c:1921
        grab_widget = 0xcd91d0 [GtkXournal]
        window_group = 0x1640ab0 [GtkWindowGroup]
        rewritten_event = <optimized out>
        device = <optimized out>
        tmp_list = <optimized out>
        event_widget = 0xcd91d0 [GtkXournal]
        topmost_widget = <optimized out>
        __func__ = "gtk_main_do_event"
#21 gtk_main_do_event (event=<optimized out>) at ../gtk/gtkmain.c:1691
        __func__ = "gtk_main_do_event"
#22 0x00007ffff673f277 in _gdk_event_emit (event=0x13025f0) at ../gdk/gdkevents.c:73
#23 _gdk_event_emit (event=0x13025f0) at ../gdk/gdkevents.c:67
#24 0x00007ffff6774ac2 in gdk_event_source_dispatch (base=<optimized out>, callback=<optimized out>, data=<optimized out>) at ../gdk/wayland/gdkeventsource.c:124
        source = <optimized out>
        display = <optimized out>
        event = 0x13025f0
#25 0x00007ffff62a78d8 in g_main_dispatch (context=0xbaacd0) at ../glib/gmain.c:3460
        dispatch = 0x7ffff6774aa0 <gdk_event_source_dispatch>
        prev_source = 0x0
        begin_time_nsec = 0
        was_in_call = 0
        user_data = 0x0
        callback = 0x0
        cb_funcs = 0x0
        cb_data = 0x0
        need_destroy = <optimized out>
        source = 0xbddf60
        current = 0xbbf2b0
        i = 0
        __func__ = "g_main_dispatch"
#26 g_main_context_dispatch (context=context@entry=0xbaacd0) at ../glib/gmain.c:4200
#27 0x00007ffff62a7ce8 in g_main_context_iterate (context=context@entry=0xbaacd0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4276
        max_priority = 0
        timeout = 0
        some_ready = 1
        nfds = <optimized out>
        allocated_nfds = 3
        fds = 0x1635400
#28 0x00007ffff62a7d7c in g_main_context_iteration (context=context@entry=0xbaacd0, may_block=may_block@entry=1) at ../glib/gmain.c:4343
        retval = <optimized out>
#29 0x00007ffff650583d in g_application_run (application=0xba8e10 [GtkApplication], argc=1, argv=<optimized out>) at ../gio/gapplication.c:2573
        arguments = 0xb698c0
        status = 0
        context = 0xbaacd0
        acquired_context = <optimized out>
        __func__ = "g_application_run"
#30 0x000000000078b781 in XournalMain::run(int, char**) ()
#31 0x00000000007849ab in main ()
```

</p>
</details>

**Comment by rolandlo** [comment]
I have failed to reproduce the issue. Does it only happen with the Wacom tablet or can you also do it just using the mouse/touchpad?
It's an assertion failure. The assertion was that the selection can only have been attempted to be created a second time if it was created via a stylus button press while the stylus was hovering and the "Merge button events with stylus tip events" option is activated. For some reason that assertion was not true in your case.

**Comment by mesonium** [comment]
> I have failed to reproduce the issue. 

I have played around and found that my former "how to reproduce" description was not quiet correct.

The assert seems to trigger when you use the tablet pen to draw a rectangular selection, which goes beyond Xouralpp's window. 
Then - being outside of the window - you take off the pen: The selection within Xournalpp's page stays. (*) 
Now you click with the pen or mouse into Xournalpp's page again.

(*) This I could only reproduce with the Wacom tablet, not with a mouse or touchpad.

Here's a screen recording:

https://github.com/xournalpp/xournalpp/assets/93607429/9715b37d-5c34-4fc1-a072-1ec40ad18571

**Comment by mesonium** [comment]
The selection also stays in RNote when doing the equivalent steps there. However, in RNote no assertion test fails in the end. :)

**Comment by mesonium** [comment]
The relevant commit, which introduced the assert was the following: https://github.com/xournalpp/xournalpp/commit/1e833503496afb4638ba189d66f977c13ec9d388
Locally I have patched the assert out for now with no downsides so far.
