### ISSUE TITLE
 Unable to Run xournalpp.exe on Windows (Version 1.2.3)

### ISSUE THREAD

**Issue by XiaoboMa1** [xournalpp/xournalpp#5868]
### Operating System

Windows

### (Linux Only) Display Server

None

### Installation Method

Official release

### Xournal++ Version

1.2.3

### libgtk Version

1.2.3

### Bug Description

I have downloaded and extracted the portable version of Xournal++ 1.2.3 for Windows. However, when I try to run xournalpp.exe, nothing happens — there is no error message, and the application does not launch. I have tried running it as an administrator and have ensured that my system meets the necessary requirements, including having GTK3 and Visual C++ Redistributable installed.

Here are the steps I've taken to troubleshoot:

Ran the executable as an administrator.
Checked my antivirus and firewall settings to ensure they are not blocking the application.
Verified that the download was complete and not corrupted.
Checked the Event Viewer for any error logs related to Xournal++ but found no relevant entries.
Despite these attempts, the issue persists. Could you please provide guidance on what might be causing this problem or how to resolve it?

### Expected Behaviour

Being able to run the programme as normal

### Steps to Reproduce

Download the Installation Package: Download the portable version 1.2.3 of Xournal++ from the official website.

Extract and Install: Extract the downloaded archive and run the setup program contained in xournalpp-1.2.3-windows.zip.

Installation Completion: Follow the installation steps. After the installation process completes, it displays a "completed" message indicating the installation is finished.

Executable Missing or Unresponsive: Navigate to the installation directory. In the bin folder, find the xournalpp.exe file. Double-click on xournalpp.exe, but nothing happens — the program does not launch, and no error messages are displayed.

![屏幕截图 2024-09-16 232438](https://github.com/user-attachments/assets/3859744a-d7fb-46c0-8a44-a39c0ba8b016)
![屏幕截图 2024-09-17 175259](https://github.com/user-attachments/assets/18c36a13-fff9-48db-a87c-53a3a3cfde9a)

**Comment by rolandlo** [comment]
The one thing you can do to debug the problem is installing [MSYS2](https://www.msys2.org/) and run `xournalpp.exe` from the MSYS2 console (after changing directory to the folder containing the executable). Then you should see the output that xournalpp creates.

**Comment by Universal-Invariant** [comment]
Same problem.

```

$ ./xournalpp.exe
Fontconfig error: Cannot load default config file: No such file: (null)

(com.github.xournalpp.xournalpp:84160): xopp-WARNING **: 20:11:51.804: XournalMain: System default locale could not be set.
 - Caused by: locale::facet::_S_create_c_locale name not valid
 - Note that it is not supported to set the locale using mingw-w64 on windows.
 - This could be solved by compiling xournalpp with msvc
**
Gtk:ERROR:../gtk-3.24.51/gtk/gtkiconhelper.c:495:ensure_surface_for_gicon: assertion failed (error == NULL): Icon 'image-missing' not present in theme Adwaita (gtk-icon-theme-error-quark, 0)
Bail out! Gtk:ERROR:../gtk-3.24.51/gtk/gtkiconhelper.c:495:ensure_surface_for_gicon: assertion failed (error == NULL): Icon 'image-missing' not present in theme Adwaita (gtk-icon-theme-error-quark, 0)



*************************************************************************

[Crash Handler] Crashed 1 time(s) with signal 22
xournalpp 1.3.2 (89f9b3e5 from /)
├──libgtk: 3.24.51
├──glib: 2.86.3
├──cairo:  1.18.4
├──GDK backend: Win32
└──OS info: Windows 11 24H2


Try to get a stacktrace...
Stack trace (most recent call first):
#0  0x00007ff69c97a565 in Stacktrace::printStacktrace(std::ostream&) at D:/a/xournalpp/xournalpp/src/util/Stacktrace.cpp:15:29
#1  0x00007ff69c7b2149 in crashHandler at D:/a/xournalpp/xournalpp/src/core/control/CrashHandler.cpp:58:36
```

That was from running in a msys shell but it fails running it normally.

**Comment by bhennion** [comment]
@Universal-Invariant Your issue may not have the same cause. I opened a dedicated ticket for it #7133 

I will also be closing this one as it is stale and we do not have enough information to locate the issue.
