### ISSUE TITLE
Crash on Arch Linux after some time

### ISSUE THREAD

**Issue by Bl4d3s** [xournalpp/xournalpp#802]
I'm running the latest kernel and latest xournalpp build on an Lenovo Thinkpad Yoga 370, it crashes sometimes but not after certain actions, but random. If I then restart xournalpp it asks if I want to restore, if I select it right then it crashes again. If I wait till the pdf is loaded in the background and then click restore it works again.

If you need additional information feel free to ask.

Here is the gdb stacktrace.

```
Starting program: /usr/bin/xournalpp 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff007a700 (LWP 2615)]
[New Thread 0x7fffef879700 (LWP 2616)]
[New Thread 0x7fffee59d700 (LWP 2617)]
[New Thread 0x7fffedd9c700 (LWP 2618)]
[Thread 0x7fffee59d700 (LWP 2617) exited]
[New Thread 0x7fffee59d700 (LWP 2625)]
[New Thread 0x7fffed2fe700 (LWP 2626)]
[New Thread 0x7fffcffff700 (LWP 2627)]
[Thread 0x7fffed2fe700 (LWP 2626) exited]
[Thread 0x7fffee59d700 (LWP 2625) exited]

** (xournalpp:2611): WARNING **: 09:49:41.289: Input for the same device started twice!

** (xournalpp:2611): WARNING **: 09:49:41.952: Input for the same device started twice!

** (xournalpp:2611): WARNING **: 09:49:44.317: Input for the same device started twice!

** (xournalpp:2611): WARNING **: 09:49:48.591: Input for the same device started twice!
[New Thread 0x7fffee59d700 (LWP 2673)]
[New Thread 0x7fffed2fe700 (LWP 2674)]
[Thread 0x7fffed2fe700 (LWP 2674) exited]
[Thread 0x7fffee59d700 (LWP 2673) exited]

** (xournalpp:2611): WARNING **: 09:50:54.733: Input for the same device started twice!

** (xournalpp:2611): WARNING **: 09:50:59.577: Input for the same device started twice!

** (xournalpp:2611): WARNING **: 09:51:08.352: Input for the same device started twice!
[New Thread 0x7fffee59d700 (LWP 2687)]
[New Thread 0x7fffed2fe700 (LWP 2688)]
[Thread 0x7fffed2fe700 (LWP 2688) exited]
[Thread 0x7fffee59d700 (LWP 2687) exited]
[New Thread 0x7fffed2fe700 (LWP 2690)]
[Thread 0x7fffed2fe700 (LWP 2690) exited]
[New Thread 0x7fffed2fe700 (LWP 2694)]
[New Thread 0x7fffee59d700 (LWP 2695)]
[Thread 0x7fffee59d700 (LWP 2695) exited]

** (xournalpp:2611): WARNING **: 09:51:53.281: Input for the same device started twice!
[Thread 0x7fffed2fe700 (LWP 2694) exited]
[New Thread 0x7fffed2fe700 (LWP 2697)]
[New Thread 0x7fffee59d700 (LWP 2698)]
[Thread 0x7fffed2fe700 (LWP 2697) exited]
[Thread 0x7fffee59d700 (LWP 2698) exited]
[New Thread 0x7fffee59d700 (LWP 2711)]
[New Thread 0x7fffed2fe700 (LWP 2712)]
[Thread 0x7fffed2fe700 (LWP 2712) exited]
[Thread 0x7fffee59d700 (LWP 2711) exited]

** (xournalpp:2611): WARNING **: 09:53:22.791: Input for the same device started twice!

** (xournalpp:2611): WARNING **: 09:53:31.739: Input for the same device started twice!

Thread 1 "xournalpp" received signal SIGSEGV, Segmentation fault.
0x00005555557325d1 in NewGtkInputDevice::getXournal() ()
(gdb) bt
#0  0x00005555557325d1 in NewGtkInputDevice::getXournal() ()
#1  0x0000555555730909 in  ()
#2  0x0000555555731de4 in  ()
#3  0x00005555557c1f94 in std::function<void ()>::operator()() const ()
#4  0x00005555557c0c29 in  ()
#5  0x00007ffff7627b7b in  () at /usr/lib/libgdk-3.so.0
#6  0x00007ffff716c8d1 in g_main_context_dispatch ()
    at /usr/lib/libglib-2.0.so.0
#7  0x00007ffff716e5e9 in  () at /usr/lib/libglib-2.0.so.0
#8  0x00007ffff716f5c2 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#9  0x00007ffff793696f in gtk_main () at /usr/lib/libgtk-3.so.0
#10 0x0000555555683bed in XournalMain::run(int, char**) ()
#11 0x0000555555649f5e in main ()
(gdb) 
```

Here an output of xinput
```
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ ETPS/2 Elantech Touchpad                	id=13	[slave  pointer  (2)]
⎜   ↳ ETPS/2 Elantech TrackPoint              	id=14	[slave  pointer  (2)]
⎜   ↳ Wacom Pen and multitouch sensor Pen stylus	id=10	[slave  pointer  (2)]
⎜   ↳ Wacom Pen and multitouch sensor Pen eraser	id=16	[slave  pointer  (2)]
⎜   ↳ Wacom Pen and multitouch sensor Finger touch	id=9	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=8	[slave  keyboard (3)]
    ↳ Integrated Camera: Integrated C         	id=11	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=12	[slave  keyboard (3)]
    ↳ ThinkPad Extra Buttons                  	id=15	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
```

**Comment by peetCreative** [comment]
Thank you for reporting the bug!
Seems that the issue relates to  #764 issue. Can you try the proposd workaround there?

**Comment by Bl4d3s** [comment]
Thanks for pointing this out. Indeed the workaround mentioned there seems to fix the problem (no crashes for the last 6h)

**Comment by andreasb242** [comment]
Please configure the touch disabling in the Touch Tab.
I removed the touch devices from the device list, so this cannot be done this way.

Touch devices which are detected as touch devices in GTK are handled special, this causes more issues than thought.
